### ISSUE TITLE
"Shift + key" shortcut is recognized as "key" press with "shift" key ignored

### ISSUE THREAD

**Issue by serpheroth** [hluk/FakeVim#17]
In my .vimrc
I set the "space" key to move to the line end and "shift + space" to move to start of the line. It works well in vim. But in fakevim, it recognizes "shift + space" combination as "space" key. Does fakevim intentionally ignore the pressed "shift" key? Or it is a feature that will be added?

**Comment by MichaelVoelkel** [comment]
I get here when I google and it still does not work
