### ISSUE TITLE
Using plugins with FakeVim

### ISSUE THREAD

**Issue by morodeer** [hluk/FakeVim#31]
Hello, I'm wondering if there is a possibility to use plugins with fakeVim? I understand, that functionality for modifying viewing area (like in EasyType) might be hard to implement, but maybe at least only-input plugins might be made to work? (Like vim-arpeggio which I use a lot on usual vim)

**Comment by hluk** [comment]
That's not really possible -- it would require to implement parser for Vim's scripting language.

It's not even goal of the project. FakeVim implements only some of the standard Vim commands and the underlying editor widget should provide any additional functionality.

**Comment by Doug233** [comment]
I noticed that Qt Creator's FakeVim [documentation ](https://doc.qt.io/qtcreator/creator-reference-preferences-fakevim.html#emulating-plugins)supports 5 specific plugins. Is it possible to use them in CopyQ's FakeVim? @hluk

**Comment by hluk** [comment]
> I noticed that Qt Creator's FakeVim [documentation ](https://doc.qt.io/qtcreator/creator-reference-preferences-fakevim.html#emulating-plugins)supports 5 specific plugins. Is it possible to use them in CopyQ's FakeVim? [@hluk](https://github.com/hluk)

Not sure how easy it would be to support the plugins, but I'm not planning on doing any work myself for FakeVim in the near future.
