### ISSUE TITLE
:w does not behave same as Ctrl-S

### ISSUE THREAD

**Issue by guoxiao** [hluk/FakeVim#36]
I set the beautifier plugin to automatically format source files when saved, but in fakevim mode, `:w` doesn't trigger it.
If I choose `Save` from `File` menu, the formatter is triggered. 

Now I have to enable `Pass control key` in fakevim settings and press `Ctrl-S` to trigger formatting. 
Should we change the behaviour and make `:w` work same as `Ctrl-S` ?

**Comment by hluk** [comment]
This is handled in Qt Creator -- [here is the code](https://github.com/qtproject/qt-creator/blob/9fda4907f289290243604736031e788edc6e932f/src/plugins/fakevim/fakevimplugin.cpp#L1995).

Seems that calling `DocumentManager::saveDocument()` doesn't trigger other plugins. Do you see any difference with ":wa"?

Maybe using `triggerAction(Core::Constants::SAVE)` instead would solve the issue.

**Comment by hluk** [comment]
Code review: https://codereview.qt-project.org/#/c/183055/

**Comment by hluk** [comment]
It's in master branch of Qt Creator -- will be fixed in some future version.
