### ISSUE TITLE
Feature request: ":set nu" and ":set rnu"

### ISSUE THREAD

**Issue by cognifloyd** [hluk/FakeVim#37]
I would like to be able to turn line numbers on/off on the fly in ReText (thanks a million for making FakeVim with python bindings!). I think that in order to get this, FakeVim would need a way to get a `:set nu` or `:set number` command and pass it on to the app that has embedded a FakeVim editor.

I would also love relative line numbers `:set rnu` or `:set relatienumber`.

ReText already has line numbers that can be enabled/disabled via a preferences dialog, but would need to implement something for relative line numbers. Now, all that's needed (at least for `:set nu`) is a way for FakeVim to send the command to ReText. Once FakeVim has support for this, I'll file feature requests in ReText to use the new FakeVim features.

**Comment by hluk** [comment]
This is already possible and it's used by Qt Creator.

You can handle any commands in [this function](https://github.com/retext-project/retext/blob/108d3b1c882727859525cd6be3a277ac9585cb20/ReText/fakevimeditor.py#L76). E.g.

```python
if cmd.matches('se', 'set'):
    if cmd.args == 'relativenumber' or cmd.args == 'rnu':
        ...
    elif cmd.args == 'norelativenumber' or cmd.args == 'nornu':
        ...
    else:
        return false # Return false so FakeVim can handle other options.
```
