### ISSUE TITLE
fakevimConfig.cmake includes a nonexistent file "fakevimTargets.cmake"

### ISSUE THREAD

**Issue by user11681** [hluk/FakeVim#54]
[fakevimConfig.cmake](https://github.com/hluk/FakeVim/blob/da04c67ee8ca2c4eb40d7b0086031b1b04e8d71e/cmake/fakevimConfig.cmake#L1) includes a nonexistent file "fakevimTargets.cmake":
```cmake
include("${CMAKE_CURRENT_LIST_DIR}/fakevimTargets.cmake")
```

**Comment by hluk** [comment]
It is a generated file, created in build directory after invoking `cmake`.
